version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: portfolio-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:5000
    networks:
      - portfolio-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: portfolio-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    networks:
      - portfolio-network
    restart: unless-stopped

networks:
  portfolio-network:
    driver: bridge
