tunnel: YOUR_TUNNEL_ID_HERE
credentials-file: /home/aman/.cloudflared/ef40541a-4167-4039-85e7-55115df8b731.json

ingress:
  - hostname: racktocloud.com
    service: http://localhost:80
  - hostname: www.racktocloud.com
    service: http://localhost:80
  - hostname: api.racktocloud.com
    service: http://localhost:5000
  - service: http_status:404
