tunnel: YOUR_TUNNEL_ID_HERE
credentials-file: /home/aman/.cloudflared/tunnel_id.json

ingress:
  - hostname: racktocloud.com
    service: http://localhost:80
  - hostname: www.racktocloud.com
    service: http://localhost:80
  - hostname: api.racktocloud.com
    service: http://localhost:5000
  - service: http_status:404
