name: Deploy Portfolio

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Use your self-hosted runner
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build and Deploy
      run: |
        echo "Building and deploying portfolio..."
        
        # Navigate to portfolio directory
        cd /home/$USER/aman-portfolio || cd ~/aman-portfolio
        
        # Pull latest changes
        git pull origin main
        
        # Stop existing containers
        docker compose down || docker-compose down
        
        # Build and start new containers
        docker compose up -d --build || docker-compose up -d --build
        
        # Clean up old images
        docker system prune -f
        
        echo "Deployment completed!"
    
    - name: Health Check
      run: |
        sleep 10
        curl -f http://localhost/api/health || exit 1
        echo "Health check passed!"
